### ISSUE TITLE
Internal Patcher doesnt seem to work for me

### ISSUE THREAD

**Issue by EasternBloxxer** [Bork0038/studio-patcher#2]
![image](https://user-images.githubusercontent.com/54174182/227661291-6e7863ea-4874-4309-8aca-c5a2e847ec81.png)

**Comment by Bork0038** [comment]
omw home issue will be fixed in an hour or two, roblox changed some wacky shit

**Comment by Bork0038** [comment]
I cannot replicate the issue, please contact me on discord. chris!#0038
![image](https://user-images.githubusercontent.com/71100852/227695817-5f389e97-3777-4224-ac1b-c89100ef91cc.png)

**Comment by Bork0038** [comment]
fixed, when rewriting some of the application I messed up the borrowing
