### ISSUE TITLE
Internal Studio doesn't work once again

### ISSUE THREAD

**Issue by alpharetzy** [Bork0038/studio-patcher#3]
when trying to install the internal studio patch, it doesn't work anymore.

i looked in the executable and noticed it now says HasInternalPermission instead of hasInternalPermission

**Comment by Bork0038** [comment]
> when trying to install the internal studio patch, it doesn't work anymore.
> 
> 
> 
> i looked in the executable and noticed it now says HasInternalPermission instead of hasInternalPermission
https://github.com/7ap/internal-studio-patcher use this instead for now, i'm working on a full rewrite rn.

**Comment by alpharetzy** [comment]
> > when trying to install the internal studio patch, it doesn't work anymore.
> > i looked in the executable and noticed it now says HasInternalPermission instead of hasInternalPermission
> 
> https://github.com/7ap/internal-studio-patcher use this instead for now, i'm working on a full rewrite rn.

how do I use it? i opened an issue in that repository but i got no response
